<?php

namespace AppWebBundle\Repository;

/**
 * CompromissoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompromissoRepository extends \Doctrine\ORM\EntityRepository
{
}
