<?php

namespace AppWebBundle\Repository;

/**
 * ContatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUserId($user_id) {
               
        $qb = $this->createQueryBuilder('c');
        
        $qb->select(
                    'c.id',
                    'c.nome',
                    'c.email',
                    'c.telefone',
                    'c.status',
                    'c.sync',
                    'c.createdAt',
                    'c.updatedAt',
                    'u.id as user'
                )
                ->join('AppWebBundle:User', 'u', "WITH", "u = c.user")
                ->where('u.id = :id')
                ->setParameter('id', $user_id);
                        
        return $qb->getQuery()->getResult();
    }

	public function findByIdAndUserId($id, $user_id) {
               
        $qb = $this->createQueryBuilder('c');
        
        $qb->select(
                    'c.id',
                    'c.nome',
                    'c.email',
                    'c.telefone',
                    'c.status',
                    'c.sync',
                    'c.createdAt',
                    'c.updatedAt',
                    'u.id as user'
                )
                ->join('AppWebBundle:User', 'u', "WITH", "u = c.user")
                ->where('c.id = :id')
                ->Andwhere('u.id = :user_id')
                ->setParameter('id', $id)
                ->setParameter('user_id', $user_id);
                
        return $qb->getQuery()->getResult();
    }
}
